GI - Grammar Inference: gi::lstar Class Reference
gi::lstar Class Reference
#include <lstar.h>
Public Member Functions
lstar (const dfa &targetdfa)
~lstar ()
dfa run_lstar (bool approximate, string samplestestpath)
vector< obtState > get_row (vector< SYMBOL > prefix)
bool close_obt ()
bool make_obt_consistent ()
void update_from_counterexample (vector< SYMBOL > witness)
dfa * obt_to_dfa ()
void print_obt ()
Private Attributes
vector< vector< SYMBOL > > experiments
map< vector< SYMBOL >, bool > mq
map< vector< SYMBOL >
, obtState,
vector_int_size_less > pref
unsigned short int dim_alfabeto
vector< SYMBOL > * alfabeto
dfa * target
Detailed Description
Definition at line 36 of file lstar.h.
Constructor & Destructor Documentation
lstar::lstar (const dfa & targetdfa)
Instance an object with all the members and methods for LSTAR inference process.
Parameters
path It's the target DFA for the inference process, used from Teacher.
Definition at line 21 of file lstar.cpp.
References alfabeto, dim_alfabeto, experiments, gi::dfa::get_dim_alphabet(), gi::dfa::membership_query(), mq, OBT_STATE_BLU, OBT_STATE_RED, pref, and target.
lstar::~lstar ()
Destroy an LSTAR object, freeing the memory.
Definition at line 52 of file lstar.cpp.
Member Function Documentation
bool lstar::close_obt ()
For a non closed table, fix one or more problems (not necessary all) which keep not closed the table.
Returns
Return 'true' if the table was modified (DOESEN'T mean table is closed!). Otherwise return 'false', that is: table was not modified, it was already closed.
Definition at line 62 of file lstar.cpp.
References append_vectors(), OBT_STATE_BLU, and OBT_STATE_RED.
Referenced by run_lstar().
vector< obtState > lstar::get_row (vector< SYMBOL > prefix)
Return a whole "row" of Observation Table for a prefix.
Parameters
prefix Unique prefix labeling a row.
Returns
Row of observation table
Definition at line 427 of file lstar.cpp.
References OBT_STATE_BLU, and OBT_STATE_RED.
bool lstar::make_obt_consistent ()
For a non consistent table, fix one or more problems (not necessary all) which keep not consistent the table.
Returns
Return 'true' if the table was modified (DOESEN'T mean table is consistent!). Otherwise return 'false', that is: table was not modified, it was already consistent.
Definition at line 145 of file lstar.cpp.
References append_vectors(), and OBT_STATE_RED.
Referenced by run_lstar().
gi::dfa * lstar::obt_to_dfa ()
Build a DFA from Observation Table.
Returns
Pointer to builded DFA.
Definition at line 234 of file lstar.cpp.
References append_vectors(), gi::dfa::get_ttable(), and OBT_STATE_RED.
Referenced by run_lstar().
void lstar::print_obt ()
Print the Observation table.
Definition at line 380 of file lstar.cpp.
References append_vectors().
Referenced by run_lstar().
gi::dfa lstar::run_lstar (bool approximate, string samplestestpath)
Start an LSTAR inference process.
Parameters
approximate If it's true, set an LSTAR inference process using an approximation of target DFA.
samplestestpath Samples approximating target DFA.
Returns
The
Definition at line 441 of file lstar.cpp.
References close_obt(), make_obt_consistent(), gi::dfa::minimize_TF(), obt_to_dfa(), gi::dfa::print_dfa_ttable(), print_obt(), and update_from_counterexample().
Referenced by main().
void lstar::update_from_counterexample (vector< SYMBOL > witness)
Update the table using the witness.
Parameters
witness Witness is the counterexample coming from Teacher.
Definition at line 343 of file lstar.cpp.
References append_vectors(), OBT_STATE_BLU, OBT_STATE_RED, and prefix_vector().
Referenced by run_lstar().
Member Data Documentation
vector<SYMBOL>* gi::lstar::alfabeto private
Alphabet
Definition at line 46 of file lstar.h.
Referenced by lstar().
unsigned short int gi::lstar::dim_alfabeto private
Alphabet size
Definition at line 45 of file lstar.h.
Referenced by lstar().
vector<vector<SYMBOL> > gi::lstar::experiments private
Columns of Observation Table
Definition at line 41 of file lstar.h.
Referenced by lstar().
map<vector<SYMBOL>, bool> gi::lstar::mq private
Local values of results for membership query already asked to Teacher
Definition at line 42 of file lstar.h.
Referenced by lstar().
map<vector<SYMBOL>, obtState, vector_int_size_less> gi::lstar::pref private
Blue and red prefixes of Observation Tables
Definition at line 43 of file lstar.h.
Referenced by lstar().
dfa* gi::lstar::target private
Target DFA of inference process. Used from Teacher.
Definition at line 48 of file lstar.h.
Referenced by lstar().
The documentation for this class was generated from the following files:
lstar.h
lstar.cpp