GI - Grammar Inference: gi::edsm Class Reference
gi::edsm Class Reference
#include <edsm.h>
Public Member Functions
edsm (const char *path)
~edsm ()
dfa run (string path)
edsm (const char *path)
~edsm ()
dfa run (string path)
Public Member Functions inherited from gi::bluefringe
bluefringe (const char *path)
virtual ~bluefringe ()
Private Member Functions
int merge_heuristic_score (dfaEDSM *dfa1, vector< SYMBOL > *positive, int dim_positive, vector< SYMBOL > *negative, int dim_negative)
double merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states)
int merge_heuristic_score (dfaEDSM *dfa1, vector< SYMBOL > *positive, int dim_positive, vector< SYMBOL > *negative, int dim_negative)
Private Attributes
string base_path
string user
bool edsm
bool blueStar
Additional Inherited Members
Protected Member Functions inherited from gi::bluefringe
void read_samples (vector< SYMBOL > *&positive, int *dim_positive, vector< SYMBOL > *&negative, int *dim_negative)
dfaEDSM * build_apta (const vector< SYMBOL > *positive, const int dim_positive, const vector< SYMBOL > *negative, const int dim_negative)
void merge (dfaEDSM *dfa1, int q1, int q2)
void fold (dfaEDSM *originale, int q1, int q2)
void promote (dfaEDSM *dfa1, int q)
void nuoviBlu (dfaEDSM *dfa1)
void eliminaStati (dfaEDSM *dfa1)
void set_fringe_size (int r, int b)
void print_fringe_size ()
int get_actual_merge ()
int get_heuristic_merge ()
int get_while_count ()
Protected Attributes inherited from gi::bluefringe
char * path_samples
int dim_alphabet
map< char, int > mapped_alphabet
char * inverse_mapped_alphabet
int num_actual_merge
int num_heuristic_merge_valued
vector< int > fringe_size [2]
int while_count
Detailed Description
Definition at line 27 of file edsm.h.
Constructor & Destructor Documentation
gi::edsm::edsm (const char * path)
Update the 'dfa1' adding new blue states. Every state, that is achievable from a red state is promoted to blue, unless arrive state is already red.
Parameters
dfa1 Set the type state to 'DEL' for that states which are unreachable from every other state: fanin=0.
dfa1 Set a new record of values that are the fringe size of blue states, and the number of red states. Every time the function is called a new snapshot is taken.
r
b Print all the snapshots taken, during EDSM process, about the fringe size. It's a function with statistical finality. Return the number of merges already performed to the actual stage of EDSM process.
Returns
Number of merges already performed to the actual stage of EDSM process. It's a function with statistical finality. Return the number of all simulated merges for heuristic evaluation, from first to actual stage.
Number of all simulated merges for heuristic evaluation to actual stage. It's a function with statistical finality. Return the number of iteration of EDSM: it's the number of times that EDSM finded that there was already blue states.
Instance an object with all the members and methods for EDSM inference process.
Parameters
path It's the path where find positive and negative samples
edsm::~edsm ()
Destroy and EDSM object, freeing the memory.
Definition at line 45 of file edsm.cpp.
gi::edsm::edsm (const char * path)
Instance an object with all the members and methods for EDSM inference process.
Parameters
path It's the path where find positive and negative samples
gi::edsm::~edsm ()
Destroy and EDSM object, freeing the memory.
Member Function Documentation
int gi::edsm::merge_heuristic_score (dfaEDSM * dfa1, vector< SYMBOL > * positive, int dim_positive, vector< SYMBOL > * negative, int dim_negative) private virtual
Return a score for a dfa. It's calculated by heuristic emerged during Abbadingo Competition (1998).
Parameters
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better.
Implements gi::bluefringe.
int edsm::merge_heuristic_score (dfaEDSM * dfa1, vector< SYMBOL > * positive, int dim_positive, vector< SYMBOL > * negative, int dim_negative) private virtual
Read positive and negative samples, and copy them inside 'positive' and 'negative' vector in parameters.
Parameters
positive
dim_positive
negative
dim_negative Build an APTA (Augmented Prefix Tree Acceptor) with positive and negative samples, extracted by read_samples().
positive
dim_positive
negative
dim_negative
Returns
A pointer to built APTA. Perform a merge operation between state q1 and state q2, for DFA dfa1.
Parameters
dfa1
q1
q2 Perform a recursive operation of fold, starting from the states to merge, inside "originale" dfa.
originale
q1
q2 Promote the state q, from blue to red state. Delete the state from the blue state list.
dfa1
q Return a score for a dfa. It's calculated by heuristic emerged during Abbadingo Competition (1998).
dfa1
positive
dim_positive
negative
dim_negative
Returns
A score for a DFA, greater is better.
Implements gi::bluefringe.
Definition at line 48 of file edsm.cpp.
References db, gi::dfa::get_arrive_state(), gi::dfa::get_num_states(), MINF, and ND.
double gi::edsm::merge_heuristic_score (double error_rate_before, double error_rate_after, int dim_strings, double alpha, int earn_states) inline private virtual
Implements gi::bluefringe.
Definition at line 92 of file edsm.h.
dfa gi::edsm::run (string path) virtual
Start an EDSM inference process.
Parameters
path It's the base path where create all the output files of EDSM.
Returns
Inferred DFA
Implements gi::bluefringe.
gi::dfa edsm::run (string path) virtual
Start an EDSM inference process.
Parameters
path It's the base path where create all the output files of EDSM.
Returns
Inferred DFA
Implements gi::bluefringe.
Definition at line 117 of file edsm.cpp.
References DFA_STATE_REJECTING, gi::dfa::get_arrive_state(), gi::dfaEDSM::get_blue_states(), gi::dfa::get_dim_alphabet(), gi::dfaEDSM::get_num_blue_states(), gi::dfaEDSM::get_num_red_states(), gi::dfa::get_num_states(), gi::dfaEDSM::get_red_states(), gi::dfa::get_ttable(), intTostring(), MINF, gi::dfa::minimize_TF(), ND, gi::dfaEDSM::print_dfa_dot(), gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), and gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
Referenced by main().
Member Data Documentation
string gi::edsm::base_path private
Base path for the experiment
Definition at line 31 of file geoExp.h.
bool gi::edsm::blueStar private
Definition at line 37 of file geoExp.h.
edsm::edsm private
Definition at line 35 of file geoExp.h.
string gi::edsm::user private
Definition at line 33 of file geoExp.h.
The documentation for this class was generated from the following files:
edsm.h
geoExp.h
edsm.cpp
geoExp.cpp