GI - Grammar Inference: gi::dfa Class Reference
gi::dfa Class Reference
#include <dfa.h>
Public Member Functions
dfa ()
dfa (const int n_state, const int dim_alf, const char *alf)
dfa (const int n_state, const int dim_alf, const char *alf, const int s_state)
dfa (const int n_state, const int dim_alf, const char *alf, const int s_state, const int **tt_copy)
dfa (const dfa &d1)
~dfa ()
int get_dim_alphabet ()
char * get_alphabet ()
int get_num_states ()
int get_start_state ()
int get_arrive_state (vector< SYMBOL > dfa_string)
int ** get_ttable ()
int get_ttable (int i, int j)
void set_ttable_entry (int i, int j, int v)
void set_acceptor_state (int state)
void set_rejector_state (int state)
dfa * unionDFA (dfa *dfa_hp)
dfa * minimize_TF ()
void print_dfa_ttable (string title)
void print_dfa_ttable_mapped_alphabet (string title)
void print_dfa_dot (string title, const char *file_path)
void print_dfa_dot_mapped_alphabet (string title, const char *file_path)
void read_example_file (string path_samples, vector< SYMBOL > *&positive, int *dim_positive, vector< SYMBOL > *&negative, int *dim_negative)
bool membership_query (vector< SYMBOL > str)
vector< SYMBOL > equivalence_query (dfa *dfa_hp)
SYMBOL * table_filling ()
vector< int > * equivalent_states_list_from_table (SYMBOL *distincts)
vector< SYMBOL > witness_from_table (SYMBOL *distinct, int start_state_dfa_hp)
vector< SYMBOL > equivalence_query_approximate (dfa *dfa_hp, string samplestestpath)
vector< SYMBOL > witness_approximate (dfa *dfa_hp, string samplestestpath)
Static Public Member Functions
static dfa read_dfa_file (const string file_name)
Protected Member Functions
void set_ttable (int **ext_ttab)
void set_num_state (int n)
void set_alphabet (const char *alf, const int d_alf)
Protected Attributes
int ** ttable
int num_states
int start_state
int dim_alphabet
char * alphabet
map< char, SYMBOL > mapped_alphabet
Detailed Description
Definition at line 37 of file dfa.h.
Constructor & Destructor Documentation
dfa::dfa ()
Make an instance of null dfa
Definition at line 26 of file dfa.cpp.
dfa::dfa (const int n_state, const int dim_alf, const char * alf)
Make an instance of new dfa with default start state to 0
Parameters
n_state Number of states
dim_alf Size of alphabet
alf Alphabet symbols
Definition at line 60 of file dfa.cpp.
dfa::dfa (const int n_state, const int dim_alf, const char * alf, const int s_state)
Make an instance of new dfa. Give possibility to set the start state.
Parameters
n_state Number of states
dim_alf Size of alphabet
alf Alphabet symbols
s_state Start state
Definition at line 36 of file dfa.cpp.
References ND.
dfa::dfa (const int n_state, const int dim_alf, const char * alf, const int s_state, const int ** tt_copy)
Make an instance of new dfa. Set tra transistion table making a copy of "tt_copy" passed as argument.
Parameters
n_state Number of states
dim_alf Size of alphabet
alf Alphabet symbols
s_state Start state
tt_copy Reference to extern transition table to copy inside current dfa
Definition at line 63 of file dfa.cpp.
References ttable.
dfa::dfa (const dfa & d1)
Constructor for make a copy of a dfa "d1"
Parameters
d1 Dfa to copy
Definition at line 72 of file dfa.cpp.
dfa::~dfa ()
Destroy a DFA object, freeing the memory.
Definition at line 77 of file dfa.cpp.
Member Function Documentation
vector< SYMBOL > dfa::equivalence_query (dfa * dfa_hp)
Make an equivalence query, that return an empty witness if the current dfa is equivalent to dfa "dfa_hp", argument of the function. Otherwise return a witness, that is a counterexample that distinguishes the two dfa.
Parameters
dfa_hp Pointer to dfa to compare for equivalence.
Returns
A conterexample, empty if the two dfa are equivalent.
Definition at line 1144 of file dfa.cpp.
References equivalent_states_list_from_table(), print_dfa_ttable(), table_filling(), and witness_from_table().
vector< SYMBOL > dfa::equivalence_query_approximate (dfa * dfa_hp, string samplestestpath)
Like the equivalence query function, but it not generate the witness but use a limitated set of string where select the conterexample.
Parameters
dfa_hp Pointer to dfa to compare for equivalence.
samplestestpath Path of file with a list of counterexample.
Returns
A conterexample, empty if the two dfa are equivalent.
Definition at line 1190 of file dfa.cpp.
References equivalent_states_list_from_table(), print_dfa_ttable(), table_filling(), and witness_approximate().
vector< int > * dfa::equivalent_states_list_from_table (SYMBOL * distincts)
Create a list of states and corrispective equivalent states
Parameters
distincts A table build with the Table Filling Algorithm
Returns
A pointer to the first vector<int>. Every vector is a list of equivalent state for the state associate to that vector.
Definition at line 1334 of file dfa.cpp.
References DFA_TF_STATE_N.
Referenced by equivalence_query(), and equivalence_query_approximate().
char * dfa::get_alphabet ()
Return a pointer to alphabet symbols
Returns
Pointer to alphabet symbols
Definition at line 845 of file dfa.cpp.
Referenced by gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
int dfa::get_arrive_state (vector< SYMBOL > dfa_string)
Get index of arrive state for dfa_string argument
Parameters
dfa_string String executed on dfa
Returns
Index of arrive state for "dfa_string"
Definition at line 850 of file dfa.cpp.
References ND.
Referenced by gi::edsm::merge_heuristic_score(), gi::blueStar::run(), and gi::edsm::run().
int dfa::get_dim_alphabet ()
Return size of alphabet
Returns
Size of alphabet
Definition at line 658 of file dfa.cpp.
Referenced by gi::bluefringe::eliminaStati(), gi::bluefringe::fold(), gi::lstar::lstar(), gi::bluefringe::merge(), gi::bluefringe::nuoviBlu(), gi::bluefringe::promote(), gi::edsm::run(), and gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
int dfa::get_num_states ()
Get number of states
Returns
Number of states
Definition at line 662 of file dfa.cpp.
Referenced by gi::bluefringe::eliminaStati(), gi::bluefringe::merge(), gi::edsm::merge_heuristic_score(), gi::blueStar::run(), gi::edsm::run(), and gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
int dfa::get_start_state ()
Get index of start state
Returns
Index of start state
Definition at line 666 of file dfa.cpp.
int ** dfa::get_ttable ()
Return a reference to ttable()
Returns
Pointer to ttable
Definition at line 621 of file dfa.cpp.
Referenced by gi::bluefringe::build_apta(), gi::bluefringe::eliminaStati(), gi::bluefringe::fold(), gi::bluefringe::merge(), minimize_TF(), gi::bluefringe::nuoviBlu(), gi::lstar::obt_to_dfa(), gi::bluefringe::promote(), gi::edsm::run(), and gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
int dfa::get_ttable (int i, int j)
Get value of ttable for index "i", "j"
Parameters
i
j
Returns
Definition at line 625 of file dfa.cpp.
bool dfa::membership_query (vector< SYMBOL > str)
Make a membership query to dfa with the "str" string. Return "true" if the arrive state for "str" is acceptor, else "false".
Parameters
str A string to make a membership query.
Returns
"True" o "false" depending on the arrive state: "true" if acceptor, else if not.
Definition at line 1269 of file dfa.cpp.
References ND.
Referenced by gi::blueStar::error_rate(), gi::lstar::lstar(), and witness_approximate().
gi::dfa * dfa::minimize_TF ()
Minimizes the current dfa
Returns
Pointer to a new instance of dfa, that is the minimized current dfa
Definition at line 263 of file dfa.cpp.
References get_ttable(), ND, and print_dfa_ttable().
Referenced by gi::blueStar::run(), gi::edsm::run(), and gi::lstar::run_lstar().
void dfa::print_dfa_dot (string title, const char * file_path)
Print a dot file for the current dfa, with title "title", in the path "file_path".
Parameters
title Title printed before the transition table
file_path Path where make a dot file
Definition at line 671 of file dfa.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_REJECTING, DFA_STATE_UNREACHABLE, intTostring(), and ND.
void dfa::print_dfa_dot_mapped_alphabet (string title, const char * file_path)
Print a dot file for the current dfa using the alphabet symbols, with title "title", in the path "file_path".
Parameters
title Title printed before the transition table
file_path Path where make a dot file
Definition at line 730 of file dfa.cpp.
References charToString(), DFA_STATE_ACCEPTING, DFA_STATE_REJECTING, DFA_STATE_UNREACHABLE, intTostring(), and ND.
Referenced by main().
void dfa::print_dfa_ttable (string title)
Print the transition table of current dfa. Before the transition table print the title passse as parameter.
Parameters
title Title printed before the transition table
Definition at line 414 of file dfa.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_NON_ACCEPTING, DFA_STATE_REJECTING, intTostring(), and ND.
Referenced by equivalence_query(), equivalence_query_approximate(), main(), minimize_TF(), and gi::lstar::run_lstar().
void dfa::print_dfa_ttable_mapped_alphabet (string title)
Print the transition table using the alphabet symbols. Before the transition table print the "title".
Parameters
title Title printed before the transition table
Definition at line 458 of file dfa.cpp.
References DFA_STATE_ACCEPTING, DFA_STATE_NON_ACCEPTING, DFA_STATE_REJECTING, and ND.
gi::dfa dfa::read_dfa_file (const string file_name) static
Read a dfa from a file
Parameters
file_name Path of the dfa
Returns
Dfa read from file
Definition at line 871 of file dfa.cpp.
References BUFFER_SIZE, dim_alphabet, ND, num_states, set_alphabet(), trim(), and ttable.
Referenced by main().
void dfa::read_example_file (string path_samples, vector< SYMBOL > *& positive, int * dim_positive, vector< SYMBOL > *& negative, int * dim_negative)
Fills "positive" and "negative" vector with examples inside file in path "path_samples". Set also the number of positive and negative example in "dim_positive" and "dim_negative".
Parameters
path_samples
positive
dim_positive
negative
dim_negative
Definition at line 1007 of file dfa.cpp.
References intTostring().
void dfa::set_acceptor_state (int state)
Definition at line 646 of file dfa.cpp.
References DFA_STATE_ACCEPTING.
void dfa::set_alphabet (const char * alf, const int d_alf) protected
Set the alphabet of dfa to alphabet in input of size "d_alf". Set also "mapped_alphabet" with an index for every symbol.
Parameters
alf
d_alf
Definition at line 824 of file dfa.cpp.
Referenced by read_dfa_file().
void dfa::set_num_state (int n) protected
Set the number of states
Parameters
n
Definition at line 819 of file dfa.cpp.
void dfa::set_rejector_state (int state)
Definition at line 652 of file dfa.cpp.
References DFA_STATE_REJECTING.
void dfa::set_ttable (int ** ext_ttab) protected
Set the transition table (ttable) reference to an extern transition table passed as argument
Parameters
ext_ttab
Definition at line 617 of file dfa.cpp.
void dfa::set_ttable_entry (int i, int j, int v)
Set a single value "v" for ttable entry for "i","j"
Parameters
i First coordinate
j Second coordinate
v Value to set
Definition at line 636 of file dfa.cpp.
Referenced by gi::dfaEDSM::to_canonical_dfaEDSM_from_red_states().
SYMBOL * dfa::table_filling ()
Fills a table with the "Table Filling Algorithm", useful for find the equivalent/distinct states, and also for generate a witness. The Table considered is only the upper triangular matrix, that can be saved in a linear array.
Returns
A table saved in a linear array.
Definition at line 149 of file dfa.cpp.
References DFA_TF_STATE_N, and DFA_TF_STATE_X.
Referenced by equivalence_query(), and equivalence_query_approximate().
gi::dfa * dfa::unionDFA (dfa * dfa_hp)
Make a new dfa from the union of current dfa and "dfa_hp". The first states are from current dfa, last states from "dfa_hp". The total number of states are sum of the number of states for the 2 dfa.
Parameters
dfa_hp Dfa to add to the current dfa
Returns
Pointer to the union dfa of two dfa
Definition at line 114 of file dfa.cpp.
References num_states, and ttable.
vector< SYMBOL > dfa::witness_approximate (dfa * dfa_hp, string samplestestpath)
Used when dfa target in LSTAR is not disponibile, instead use a samples
Parameters
dfa_hp Pointer to dfa to compare for equivalence.
samplestestpath Path of file with a list of counterexample.
Returns
A witness that distinguishes the two dfa.
Definition at line 1233 of file dfa.cpp.
References membership_query().
Referenced by equivalence_query_approximate().
vector< SYMBOL > dfa::witness_from_table (SYMBOL * distinct, int start_state_dfa_hp)
Make a conterexample from a table build with Table Filling Algorithm using the union dfa of the two dfa to compare.
Parameters
distinct Table build with Table Filling Algorithm
start_state_dfa_hp Index of the first state of dfa_hp inside the union dfa
Returns
A witness that distinguishes the two dfa.
Definition at line 1284 of file dfa.cpp.
References DFA_TF_STATE_N, and DFA_TF_STATE_X.
Referenced by equivalence_query().
Member Data Documentation
char* gi::dfa::alphabet protected
Alphabet symbols
Definition at line 45 of file dfa.h.
int gi::dfa::dim_alphabet protected
Size of alphabet
Definition at line 44 of file dfa.h.
Referenced by read_dfa_file().
map<char, SYMBOL> gi::dfa::mapped_alphabet protected
Convert symbols into indices
Definition at line 46 of file dfa.h.
int gi::dfa::num_states protected
Number of dfa states
Definition at line 41 of file dfa.h.
Referenced by read_dfa_file(), and unionDFA().
int gi::dfa::start_state protected
Index of start state
Definition at line 42 of file dfa.h.
int** gi::dfa::ttable protected
Transition table
Definition at line 40 of file dfa.h.
Referenced by dfa(), read_dfa_file(), and unionDFA().
The documentation for this class was generated from the following files:
dfa.h
dfa.cpp