GI - Grammar Inference: GI-learning.cpp File Reference
GI-learning.cpp File Reference
#include <ctime>
#include <iostream>
#include <string>
#include "dfa.h"
#include "edsm.h"
#include "messages.h"
#include <boost/filesystem.hpp>
#include "lstar.h"
#include "blueStar.h"
#include "bluefringe.h"
Macros
#define SAMPLE_DIR "examples"
#define EDSM_FILE "examples.txt"
#define EDSM_FILE_BIG "examples_big.txt"
#define LSTAR_FILE "lstar.txt"
#define LSTAR_FILE_BIG "lstar_big.txt"
#define DOT_DIR "results"
#define DOT_FILE_BLUESTAR "inferredDFA_bluestar.dot"
#define DOT_FILE_EDSM "inferredDFA_edsm.dot"
#define DOT_FILE_LSTAR "inferredDFA_lstar.dot"
#define MAX_BUFFER_SIZE 256
#define BASE_PATH_EXE 0
#define MAX_ARGC 3
#define MIN_ARGC 1
Functions
void parse_input_args (int, char **, string *, string *)
string check_res_dir (const string)
int main (int argc, char *argv[])
void parse_input_args (int argc, char *argv[], string *bs, string *ls)
Macro Definition Documentation
#define BASE_PATH_EXE 0
Definition at line 38 of file GI-learning.cpp.
Referenced by main().
#define DOT_DIR "results"
Definition at line 31 of file GI-learning.cpp.
Referenced by check_res_dir(), and main().
#define DOT_FILE_BLUESTAR "inferredDFA_bluestar.dot"
Definition at line 32 of file GI-learning.cpp.
Referenced by main().
#define DOT_FILE_EDSM "inferredDFA_edsm.dot"
Definition at line 33 of file GI-learning.cpp.
Referenced by main().
#define DOT_FILE_LSTAR "inferredDFA_lstar.dot"
Definition at line 34 of file GI-learning.cpp.
Referenced by main().
#define EDSM_FILE "examples.txt"
Definition at line 25 of file GI-learning.cpp.
Referenced by parse_input_args().
#define EDSM_FILE_BIG "examples_big.txt"
Definition at line 26 of file GI-learning.cpp.
Referenced by parse_input_args().
#define LSTAR_FILE "lstar.txt"
Definition at line 28 of file GI-learning.cpp.
Referenced by parse_input_args().
#define LSTAR_FILE_BIG "lstar_big.txt"
Definition at line 29 of file GI-learning.cpp.
Referenced by parse_input_args().
#define MAX_ARGC 3
Definition at line 40 of file GI-learning.cpp.
Referenced by parse_input_args().
#define MAX_BUFFER_SIZE 256
Definition at line 37 of file GI-learning.cpp.
Referenced by check_res_dir().
#define MIN_ARGC 1
Definition at line 41 of file GI-learning.cpp.
Referenced by parse_input_args().
#define SAMPLE_DIR "examples"
Definition at line 23 of file GI-learning.cpp.
Function Documentation
string check_res_dir (const string base_path)
Definition at line 247 of file GI-learning.cpp.
References DOT_DIR, and MAX_BUFFER_SIZE.
Referenced by main().
int main (int argc, char * argv[])
Parameters
argc
argv
Returns
Definition at line 57 of file GI-learning.cpp.
References BASE_PATH_EXE, check_res_dir(), DOT_DIR, DOT_FILE_BLUESTAR, DOT_FILE_EDSM, DOT_FILE_LSTAR, gi::blueStar::get_error_rate_final_dfa(), parse_input_args(), gi::dfa::print_dfa_dot_mapped_alphabet(), gi::dfa::print_dfa_ttable(), gi::dfa::read_dfa_file(), gi::blueStar::run(), gi::edsm::run(), and gi::lstar::run_lstar().
void parse_input_args (int , char ** , string * , string *)
Referenced by main().
void parse_input_args (int argc, char * argv[], string * bs, string * ls)
Definition at line 212 of file GI-learning.cpp.
References EDSM_FILE, EDSM_FILE_BIG, LSTAR_FILE, LSTAR_FILE_BIG, MAX_ARGC, MIN_ARGC, and MSG_WRONG_ARGC.