GI - Grammar Inference: utilities.cpp File Reference
utilities.cpp File Reference
#include <utilities.h>
#include <sstream>
#include <fstream>
#include <boost/accumulators/accumulators.hpp>
#include <boost/accumulators/statistics.hpp>
Macros
#define Z_FOR_ALPHA_05 1.645
#define Z_FOR_ALPHA_025 1.96
#define Z_FOR_ALPHA_01 2.33
Functions
string intTostring (int a)
int stringToint (string str)
string charToString (char c)
string trimRight (string str)
double u_alpha_score (double alpha)
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha, double *dev_std_h0)
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha)
bool approximation_conditions_binomial_to_gaussian_distr (double p_est, double q_est, int sample_size)
Macro Definition Documentation
#define Z_FOR_ALPHA_01 2.33
Definition at line 18 of file utilities.cpp.
Referenced by u_alpha_score().
#define Z_FOR_ALPHA_025 1.96
Definition at line 17 of file utilities.cpp.
Referenced by u_alpha_score().
#define Z_FOR_ALPHA_05 1.645
Definition at line 16 of file utilities.cpp.
Referenced by u_alpha_score().
Function Documentation
bool approximation_conditions_binomial_to_gaussian_distr (double p_est, double q_est, int sample_size)
Definition at line 144 of file utilities.cpp.
Referenced by z_alpha_from_u_alpha_two_proportions_test().
string charToString (char c)
Definition at line 42 of file utilities.cpp.
Referenced by gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), and gi::dfa::print_dfa_dot_mapped_alphabet().
string intTostring (int a)
Definition at line 22 of file utilities.cpp.
Referenced by gi::dfaEDSM::print_dfa_dot(), gi::dfa::print_dfa_dot(), gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), gi::dfa::print_dfa_dot_mapped_alphabet(), gi::dfa::print_dfa_ttable(), gi::dfaEDSM::print_dfa_with_color(), gi::dfa::read_example_file(), gi::bluefringe::read_samples(), gi::blueStar::run(), and gi::edsm::run().
int stringToint (string str)
Definition at line 29 of file utilities.cpp.
string trimRight (string str)
Definition at line 52 of file utilities.cpp.
double u_alpha_score (double alpha)
Given an alpha values for a Normal Gaussian Distribution N(0,1), return the value of U_alpha, that is Z-alpha for N(0,1). It define the bound value for accepting or rejecting an hypothesis, adopting the N(0,1).
Parameters
alpha
Returns
U-alpha value: the z-value for N(0,1), the bound value for accepting and rejecting area.
Definition at line 61 of file utilities.cpp.
References Z_FOR_ALPHA_01, Z_FOR_ALPHA_025, and Z_FOR_ALPHA_05.
Referenced by z_alpha_from_u_alpha_two_proportions_test().
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha, double * dev_std_h0)
Compute the Z-alpha value for a two proportions test, for two populations, and two samples having the same size. It's a one tailed test. Z-alpha bound value for accepting and rejecting hypothesis, given an alpha value. An upper value of alpha correspond to a bigger area of rejecting state: the process will reject more merge, reducing the Type II error and increasing the Type I error. Type I error means here is: probability to reject a useful merge respect to the error introduced. It's alpha. Type II error means here is: probability to accept a dangerous merge, respecto to the error introduced. If you want an accurate final dfa you would increase the value of alpha. If you want a smaller dfa you wold decrease the value of alpha.
Parameters
prop1
prop2
sample_size
alpha
&dev_std_h0
Returns
Z-alpha value for two proportions test with 2 populations
Definition at line 87 of file utilities.cpp.
References approximation_conditions_binomial_to_gaussian_distr(), MINF, and u_alpha_score().
Referenced by gi::blueStar::merge_heuristic_score(), gi::blueStar::run(), and z_alpha_from_u_alpha_two_proportions_test().
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha)
Doesn't have the dev. std. as parameter. See the other "z_alpha_from_u_alpha_two_proportions_test" function.
Parameters
prop1
prop2
sample_size
alpha
Returns
Z-alpha value for two proportions test with 2 populations
Definition at line 137 of file utilities.cpp.
References z_alpha_from_u_alpha_two_proportions_test().