GI - Grammar Inference: utilities.h File Reference
utilities.h File Reference
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
Macros
#define ND numeric_limits<int>::max()
#define MINF numeric_limits<int>::min()
Functions
template<typename T >
vector< T > append_vectors (vector< T > *a, vector< T > *b)
template<typename T , typename Iterator >
vector< T > prefix_vector (vector< T > *a, Iterator pref_end)
template<typename T >
ostream & operator<< (ostream &os, const vector< T > obj)
string intTostring (int a)
int stringToint (string str)
string charToString (char c)
string trimRight (string str)
double u_alpha_score (double alpha)
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha, double *dev_std_h0)
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha)
bool approximation_conditions_binomial_to_gaussian_distr (double p_est, double q_est, int sample_size)
string & ltrim (string &s)
string & rtrim (string &s)
string & trim (string &s)
Macro Definition Documentation
#define MINF numeric_limits<int>::min()
Definition at line 17 of file utilities.h.
#define ND numeric_limits<int>::max()
Definition at line 16 of file utilities.h.
Function Documentation
template<typename T > vector<T> append_vectors (vector< T > * a, vector< T > * b)
Definition at line 41 of file utilities.h.
Referenced by gi::lstar::close_obt(), gi::lstar::make_obt_consistent(), gi::lstar::obt_to_dfa(), gi::lstar::print_obt(), and gi::lstar::update_from_counterexample().
bool approximation_conditions_binomial_to_gaussian_distr (double p_est, double q_est, int sample_size)
Definition at line 144 of file utilities.cpp.
Referenced by z_alpha_from_u_alpha_two_proportions_test().
string charToString (char c)
Definition at line 42 of file utilities.cpp.
Referenced by gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), and gi::dfa::print_dfa_dot_mapped_alphabet().
string intTostring (int a)
Definition at line 22 of file utilities.cpp.
Referenced by gi::dfaEDSM::print_dfa_dot(), gi::dfa::print_dfa_dot(), gi::dfaEDSM::print_dfa_dot_mapped_alphabet(), gi::dfa::print_dfa_dot_mapped_alphabet(), gi::dfa::print_dfa_ttable(), gi::dfaEDSM::print_dfa_with_color(), gi::dfa::read_example_file(), gi::bluefringe::read_samples(), gi::blueStar::run(), and gi::edsm::run().
string& ltrim (string & s) inline
Definition at line 125 of file utilities.h.
Referenced by trim().
template<typename T > ostream& operator<< (ostream & os, const vector< T > obj)
Definition at line 59 of file utilities.h.
template<typename T , typename Iterator > vector<T> prefix_vector (vector< T > * a, Iterator pref_end)
Definition at line 51 of file utilities.h.
Referenced by gi::lstar::update_from_counterexample().
string& rtrim (string & s) inline
Definition at line 131 of file utilities.h.
Referenced by trim().
int stringToint (string str)
Definition at line 29 of file utilities.cpp.
string& trim (string & s) inline
Definition at line 137 of file utilities.h.
References ltrim(), and rtrim().
Referenced by gi::dfa::read_dfa_file().
string trimRight (string str)
Definition at line 52 of file utilities.cpp.
double u_alpha_score (double alpha)
Given an alpha values for a Normal Gaussian Distribution N(0,1), return the value of U_alpha, that is Z-alpha for N(0,1). It define the bound value for accepting or rejecting an hypothesis, adopting the N(0,1).
Parameters
alpha
Returns
U-alpha value: the z-value for N(0,1), the bound value for accepting and rejecting area.
Definition at line 61 of file utilities.cpp.
References Z_FOR_ALPHA_01, Z_FOR_ALPHA_025, and Z_FOR_ALPHA_05.
Referenced by z_alpha_from_u_alpha_two_proportions_test().
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha, double * dev_std_h0)
Compute the Z-alpha value for a two proportions test, for two populations, and two samples having the same size. It's a one tailed test. Z-alpha bound value for accepting and rejecting hypothesis, given an alpha value. An upper value of alpha correspond to a bigger area of rejecting state: the process will reject more merge, reducing the Type II error and increasing the Type I error. Type I error means here is: probability to reject a useful merge respect to the error introduced. It's alpha. Type II error means here is: probability to accept a dangerous merge, respecto to the error introduced. If you want an accurate final dfa you would increase the value of alpha. If you want a smaller dfa you wold decrease the value of alpha.
Parameters
prop1
prop2
sample_size
alpha
&dev_std_h0
Returns
Z-alpha value for two proportions test with 2 populations
Definition at line 87 of file utilities.cpp.
References approximation_conditions_binomial_to_gaussian_distr(), MINF, and u_alpha_score().
Referenced by gi::blueStar::merge_heuristic_score(), gi::blueStar::run(), and z_alpha_from_u_alpha_two_proportions_test().
double z_alpha_from_u_alpha_two_proportions_test (double prop1, double prop2, int sample_size, double alpha)
Doesn't have the dev. std. as parameter. See the other "z_alpha_from_u_alpha_two_proportions_test" function.
Parameters
prop1
prop2
sample_size
alpha
Returns
Z-alpha value for two proportions test with 2 populations
Definition at line 137 of file utilities.cpp.
References z_alpha_from_u_alpha_two_proportions_test().